import Head from "next/head";
import Image from "next/image";
import Hero from "../components/Hero";
import Event from "../components/Event";
import styles from "../styles/Home.module.css";

import client from "../apollo-client";
import { gql } from "@apollo/client";

export default function Home({ conferences }: any) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero />
      <Event countries={conferences} />
    </div>
  );
}

Home.getInitialProps = async () => {
  const { data } = await client.query({
    query: gql`
      query conferences {
        conferences {
          schedules {
            day
          }
        }
      }
    `,
  });

  return { conferences: data?.conferences };
};
